name: Merge Checks
on: push

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Setup Elixir
              uses: actions/setup-elixir@v1
              with:
                otp-version: '22.2'
                elixir-version: '1.9.4'
            - name: Check Format
              run: mix format --check-formatted
            - name: Update Dependencies
              run: mix 
            - name: Run Tests
              run: mix test